services:
  ibm_apim.mgmtserver:
    class: Drupal\ibm_apim\Service\Mocks\MockAPIMServer
    arguments: [ '@tempstore.private', '@ibm_apim.restresponse_reader', '@ibm_apim.meresponse_reader' ]
    tags:
      - { name: ibm_apim }
  ibm_apim.user_utils:
    class: Drupal\ibm_apim\Service\Mocks\MockUserUtils
    arguments: [ '@current_user',
                 '@tempstore.private',
                 '@state',
                 '@logger.channel.ibm_apim',
                 '@entity_type.manager' ]
  ibm_apim.site_config:
    class: Drupal\ibm_apim\Service\Mocks\MockSiteConfig
    arguments: [ '@state',
                 '@config.factory',
                 '@logger.channel.ibm_apim',
                 '@ibm_apim.user_registry',
                 '@ibm_apim.billing',
                 '@ibm_apim.permissions',
                 '@ibm_apim.analytics',
                 '@ibm_apim.tls_client_profiles',
                 '@ibm_apim.group',
                 '@ibm_apim.vendor_extension',
                 '@plugin.manager.menu.link',
                 '@messenger',
                 '@module_handler',
                 '@module_installer']